### ISSUE TITLE
Duplicates found on songs metadata from spotify

### ISSUE THREAD

**Issue by jrubialesv** [Music-Recommendation-Engine-Project/Music-Recommendation-Engine#1]
Should we drop the duplicates or merge them?
![Screenshot 2023-02-28 105505](https://user-images.githubusercontent.com/61597804/221817763-cc57bbeb-5bdd-49a3-b42e-eff25a7dd7fc.png)

**Comment by talphaidze** [comment]
drop them. the dataset is large enough and the duplicates are creating confusion
