### ISSUE TITLE
Source of dataset

### ISSUE THREAD

**Issue by Martagdvalle** [Music-Recommendation-Engine-Project/Music-Recommendation-Engine#5]
There have been disagreements of the features and sources of the dataset, and in the meeting we weren't able to get to a decision. We give until the end of the week to solve it.

**Comment by Martagdvalle** [comment]
Juan José presented the dataset he had prepared to reinforce his perspective of the importance of each one of the features and was able to gather all together in a dataset. Everyone agreed to use that dataset for the model.

**Comment by miguelgfierro** [comment]
Love this!
